# Generated by Django 5.2.15 on 2026-06-07 21:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("summary", models.TextField()),
                ("date", models.DateTimeField(blank=True, null=True)),
                ("raw", models.JSONField(default=dict)),
                ("source", models.CharField()),
                ("link", models.URLField(unique=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Paper",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("summary", models.TextField()),
                ("date", models.DateTimeField(blank=True, null=True)),
                ("raw", models.JSONField(default=dict)),
                ("pmid", models.BigIntegerField(unique=True)),
                ("authors", models.TextField()),
                ("journal", models.CharField(max_length=255)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Trial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("summary", models.TextField()),
                ("raw", models.JSONField(default=dict)),
                ("nct_id", models.CharField(unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE_NOT_RECRUITING", "Active, not recruiting"),
                            ("APPROVED_FOR_MARKETING", "Approved for marketing"),
                            ("AVAILABLE", "Available"),
                            ("COMPLETED", "Completed"),
                            ("ENROLLING_BY_INVITATION", "Enrolling by invitation"),
                            ("NOT_YET_RECRUITING", "Not yet recruiting"),
                            ("NO_LONGER_AVAILABLE", "No longer available"),
                            ("RECRUITING", "Recruiting"),
                            ("SUSPENDED", "Suspended"),
                            ("TEMPORARILY_NOT_AVAILABLE", "Temporarily not available"),
                            ("TERMINATED", "Terminated"),
                            ("UNKNOWN", "Unknown"),
                            ("WITHDRAWN", "Withdrawn"),
                        ]
                    ),
                ),
                (
                    "phase",
                    models.CharField(
                        choices=[
                            ("PHASE1", "Phase 1"),
                            ("PHASE2", "Phase 2"),
                            ("PHASE3", "Phase 3"),
                            ("PHASE4", "Phase 4"),
                            ("PHASE1/PHASE2", "Phase 1/2"),
                            ("PHASE2/PHASE3", "Phase 2/3"),
                            ("EARLY_PHASE1", "Early Phase 1"),
                            ("NA", "N/A"),
                        ]
                    ),
                ),
                ("start_date", models.DateField(blank=True, null=True)),
                ("completion_date", models.DateField(blank=True, null=True)),
                ("last_update", models.DateField(blank=True, null=True)),
                (
                    "date",
                    models.GeneratedField(
                        db_persist=True,
                        expression=models.Case(
                            models.When(last_update__isnull=False, then="last_update"),
                            models.When(
                                completion_date__isnull=False, then="completion_date"
                            ),
                            models.When(start_date__isnull=False, then="start_date"),
                            default=None,
                            output_field=models.DateTimeField(),
                        ),
                        output_field=models.DateTimeField(),
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="FeedItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "article",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="feed.article",
                    ),
                ),
                (
                    "paper",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="feed.paper",
                    ),
                ),
                (
                    "trial",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="feed.trial",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("article__isnull", True),
                                ("paper__isnull", True),
                                ("trial__isnull", False),
                            ),
                            models.Q(
                                ("article__isnull", False),
                                ("paper__isnull", True),
                                ("trial__isnull", True),
                            ),
                            models.Q(
                                ("article__isnull", True),
                                ("paper__isnull", False),
                                ("trial__isnull", True),
                            ),
                            _connector="OR",
                        ),
                        name="only_one_content_type",
                    )
                ],
            },
        ),
    ]
