# Generated by Django 6.0.6 on 2026-06-08 23:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("feed", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="title",
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name="paper",
            name="journal",
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name="paper",
            name="title",
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name="trial",
            name="title",
            field=models.CharField(),
        ),
    ]
