# Generated by Django 6.0.6 on 2026-06-19 21:18

from django.contrib.gis.geos import Point
import django.db.models.deletion
from django.contrib.postgres.operations import CreateExtension
from django.db import migrations, models


def populate_trial_locations(apps, schema_editor):
    Trial = apps.get_model("feed", "Trial")
    TrialLocation = apps.get_model("feed", "TrialLocation")

    for trial in Trial.objects.all():
        locations = (
            trial.raw.get("protocolSection", {})
            .get("contactsLocationsModule", {})
            .get("locations", [])
        )
        trial_locations = []
        for location in locations:
            point = None
            if (
                location.get("geoPoint", {}).get("lat") is not None
                and location.get("geoPoint", {}).get("lon") is not None
            ):
                point = Point(
                    x=location["geoPoint"]["lon"],
                    y=location["geoPoint"]["lat"],
                    srid=4326,
                )
            trial_locations.append(
                TrialLocation(
                    trial=trial,
                    facility=location.get("facility", ""),
                    city=location.get("city", ""),
                    state=location.get("state", ""),
                    country=location.get("country", ""),
                    point=point,
                    raw=location,
                )
            )
        TrialLocation.objects.bulk_create(trial_locations)


class Migration(migrations.Migration):
    dependencies = [
        ("feed", "0002_alter_article_title_alter_paper_journal_and_more"),
    ]

    operations = [
        CreateExtension("postgis"),
        migrations.CreateModel(
            name="TrialLocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("facility", models.CharField(blank=True)),
                ("city", models.CharField(blank=True)),
                ("state", models.CharField(blank=True)),
                ("country", models.CharField(blank=True)),
                ("latitude", models.FloatField(blank=True, null=True)),
                ("longitude", models.FloatField(blank=True, null=True)),
                (
                    "point",
                    django.contrib.gis.db.models.fields.PointField(
                        geography=True, null=True, srid=4326
                    ),
                ),
                ("raw", models.JSONField(default=dict)),
                (
                    "trial",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="feed.trial"
                    ),
                ),
            ],
        ),
        migrations.RunPython(populate_trial_locations, migrations.RunPython.noop),
    ]
