# Generated by Django 6.0.6 on 2026-06-21 21:47

from django.db import migrations, models

from feed.models import classify_trial_relevance


def update_trial_relevance(apps, schema_editor):
    Trial = apps.get_model("feed", "Trial")
    trials = []
    for trial in Trial.objects.all():
        trial.relevance = classify_trial_relevance(trial.raw)
        trials.append(trial)
    Trial.objects.bulk_update(trials, ["relevance"])


class Migration(migrations.Migration):
    dependencies = [
        ("feed", "0003_triallocation"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="triallocation",
            name="latitude",
        ),
        migrations.RemoveField(
            model_name="triallocation",
            name="longitude",
        ),
        migrations.AddField(
            model_name="trial",
            name="relevance",
            field=models.CharField(
                choices=[("pd", "Pd"), ("related", "Related"), ("other", "Other")],
                default="other",
            ),
        ),
        migrations.AlterField(
            model_name="trial",
            name="phase",
            field=models.CharField(
                choices=[
                    ("EARLY_PHASE1", "Early Phase 1"),
                    ("PHASE1", "Phase 1"),
                    ("PHASE2", "Phase 2"),
                    ("PHASE3", "Phase 3"),
                    ("PHASE4", "Phase 4"),
                    ("PHASE1/PHASE2", "Phase 1/2"),
                    ("PHASE2/PHASE3", "Phase 2/3"),
                    ("NA", "N/A"),
                ]
            ),
        ),
        migrations.RunPython(update_trial_relevance, migrations.RunPython.noop),
    ]
